name: Build Test
on: [push]

jobs: 
  build-test:
    name: Build & Unit Test
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: ./src/package-lock.json
      - name: Install dependencies
        working-directory: ./src
        run: npm ci
      - name: Build Bundles
        working-directory: ./src
        run: npm run build
      - name: Unit Tests
        working-directory: ./src
        run: npm run test
