name: Build Test
on: [push]

jobs: 
  build-test:
    name: Build Test
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: ['16.x', '17.x', '18.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./src/package-lock.json
      - name: Install dependencies
        working-directory: ./src
        run: npm ci
      - name: Build Bundles
        working-directory: ./src
        run: npm run build
